### ISSUE TITLE
Horizontal scroll crashes UWP App 

### ISSUE THREAD

**Issue by luquettacwb** [akgulebubekir/Xamarin.Forms.DataGrid#20]
When I added DataGrid in a ScrollView, and set Scroll Orientation to HORIZONTAL, the UWP crash and the exception was:

"System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.MeasureOverride(Size availableSize)
at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.MeasureOverride(Size availableSize)
at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
at Xamarin.Forms.Plat"

[DataGrid.txt](https://github.com/akgulebubekir/Xamarin.Forms.DataGrid/files/735985/DataGrid.txt)

**Comment by akgulebubekir** [comment]
Hi,

Sorry for late response :( I've investigated this issue, unfortunately its a Xamarin bug and I've submitted this issue in bugzilla(see here)

I'm not sure if there is a workaround for this.

I will keep this thread open until they fix the issue.

**Comment by akgulebubekir** [comment]
Seems its not supported by Xamarin. ([see more](https://bugzilla.xamarin.com/show_bug.cgi?id=52349))
